### ISSUE TITLE
建议增加cmd+q退出

### ISSUE THREAD

**Issue by BosenY** [aniiantt/updrive#32]
用的很方便，很赞！

但是关闭时不可以cmd+q快捷键关闭，建议可以加一个

**Comment by aniiantt** [comment]
退出时 cmd+w 吧

**Comment by BosenY** [comment]
@aniiantt 我的意思是和mac的大多数程序一样cmd+q直接关掉应用，cmd+w好像也不是关掉整个应用

**Comment by aniiantt** [comment]
@BosenY 代码已提交，将在下一个版本更新掉
